<a href="https://colab.research.google.com/github/bjorwi69/Machine-Learning-Project/blob/main/brain-tumor-prediction/notebooks/01_data_understanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1. Import LIbraries**

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#**2. Load Dataset**

In [2]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/My Drive/Datasets/Raw/Brain_Tumor_Prediction_Dataset.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
df.head()

,Age,Gender,Country,Tumor_Size,Tumor_Location,MRI_Findings,Genetic_Risk,Smoking_History,Alcohol_Consumption,Radiation_Exposure,...,Chronic_Illness,Blood_Pressure,Diabetes,Tumor_Type,Treatment_Received,Survival_Rate(%),Tumor_Growth_Rate,Family_History,Symptom_Severity,Brain_Tumor_Present
0,66,Other,China,8.70,Cerebellum,Severe,81,No,Yes,Medium,...,Yes,122/88,No,Malignant,NaN,58,Slow,Yes,Mild,No
1,87,Female,Australia,8.14,Temporal,Normal,65,No,Yes,Medium,...,No,126/119,No,Malignant,NaN,13,Rapid,Yes,Severe,No
2,41,Male,Canada,6.02,Occipital,Severe,100,Yes,No,Low,...,No,118/65,No,Benign,Chemotherapy,67,Slow,Yes,Moderate,Yes
3,52,Male,Japan,7.26,Occipital,Normal,19,Yes,Yes,High,...,No,165/119,Yes,Benign,Radiation,85,Moderate,No,Moderate,Yes
4,84,Female,Brazil,7.94,Temporal,Abnormal,47,No,Yes,Medium,...,Yes,156/97,Yes,Malignant,NaN,17,Moderate,No,Moderate,No

In [4]:
df.tail()

,Age,Gender,Country,Tumor_Size,Tumor_Location,MRI_Findings,Genetic_Risk,Smoking_History,Alcohol_Consumption,Radiation_Exposure,...,Chronic_Illness,Blood_Pressure,Diabetes,Tumor_Type,Treatment_Received,Survival_Rate(%),Tumor_Growth_Rate,Family_History,Symptom_Severity,Brain_Tumor_Present
249995,77,Female,Germany,2.05,Frontal,Normal,9,Yes,Yes,High,...,No,93/80,Yes,Benign,Chemotherapy,36,Rapid,Yes,Mild,No
249996,89,Other,Japan,3.55,Parietal,Normal,75,Yes,No,Low,...,Yes,119/112,Yes,Benign,Radiation,80,Slow,Yes,Moderate,Yes
249997,16,Other,Russia,8.54,Temporal,Normal,52,No,Yes,Low,...,Yes,101/68,Yes,Malignant,Radiation,72,Slow,No,Severe,Yes
249998,56,Other,Germany,2.17,Cerebellum,Severe,95,Yes,No,High,...,No,179/106,Yes,Benign,NaN,83,Rapid,Yes,Moderate,Yes
249999,54,Female,Australia,5.19,Parietal,Abnormal,83,Yes,No,Medium,...,No,147/82,Yes,Malignant,Radiation,94,Slow,No,Mild,No

#**3. Dataset Shape**

In [5]:
df.shape

(250000, 21)

#**4. Dataset Information**

In [6]:
df.columns

Index(['Age', 'Gender', 'Country', 'Tumor_Size', 'Tumor_Location',
       'MRI_Findings', 'Genetic_Risk', 'Smoking_History',
       'Alcohol_Consumption', 'Radiation_Exposure', 'Head_Injury_History',
       'Chronic_Illness', 'Blood_Pressure', 'Diabetes', 'Tumor_Type',
       'Treatment_Received', 'Survival_Rate(%)', 'Tumor_Growth_Rate',
       'Family_History', 'Symptom_Severity', 'Brain_Tumor_Present'],
      dtype='object')

In [7]:
df.dtypes

Age                      int64
Gender                  object
Country                 object
Tumor_Size             float64
Tumor_Location          object
MRI_Findings            object
Genetic_Risk             int64
Smoking_History         object
Alcohol_Consumption     object
Radiation_Exposure      object
Head_Injury_History     object
Chronic_Illness         object
Blood_Pressure          object
Diabetes                object
Tumor_Type              object
Treatment_Received      object
Survival_Rate(%)         int64
Tumor_Growth_Rate       object
Family_History          object
Symptom_Severity        object
Brain_Tumor_Present     object
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Age                  250000 non-null  int64
 1   Gender               250000 non-null  object
 2   Country              250000 non-null  object
 3   Tumor_Size           250000 non-null  float64
 4   Tumor_Location       250000 non-null  object
 5   MRI_Findings         250000 non-null  object
 6   Genetic_Risk         250000 non-null  int64
 7   Smoking_History      250000 non-null  object
 8   Alcohol_Consumption  250000 non-null  object
 9   Radiation_Exposure   250000 non-null  object
 10  Head_Injury_History  250000 non-null  object
 11  Chronic_Illness      250000 non-null  object
 12  Blood_Pressure       250000 non-null  object
 13  Diabetes             250000 non-null  object
 14  Tumor_Type           250000 non-null  object
 15  Treatment_Received   187252 non-null  object
 16  Survival_Rate(%)     250000 non-null  int64
 17  Tumor_Growth_Rate    250000 non-null  object
 18  Family_History       250000 non-null  object
 19  Symptom_Severity     250000 non-null  object
 20  Brain_Tumor_Present  250000 non-null  object
dtypes: float64(1), int64(3), object(17)
memory usage: 40.1+ MB

#**5. Unique Value Analysis**

In [9]:
df.nunique()

Age                      85
Gender                    3
Country                  12
Tumor_Size              951
Tumor_Location            5
MRI_Findings              3
Genetic_Risk            101
Smoking_History           2
Alcohol_Consumption       2
Radiation_Exposure        3
Head_Injury_History       2
Chronic_Illness           2
Blood_Pressure         5551
Diabetes                  2
Tumor_Type                2
Treatment_Received        3
Survival_Rate(%)         90
Tumor_Growth_Rate         3
Family_History            2
Symptom_Severity          3
Brain_Tumor_Present       2
dtype: int64

In [10]:
for col in df.columns:
  print(df[col].value_counts())
  print()

Age
25    3061
46    3060
28    3025
39    3014
6     3011
      ...
76    2872
12    2865
64    2864
81    2855
67    2840
Name: count, Length: 85, dtype: int64

Gender
Male      83407
Female    83375
Other     83218
Name: count, dtype: int64

Country
Brazil          20985
Russia          20975
Germany         20895
China           20890
India           20883
Canada          20854
Japan           20842
USA             20792
Australia       20780
UK              20763
France          20733
South Africa    20608
Name: count, dtype: int64

Tumor_Size
0.68     318
5.23     318
6.17     309
1.75     308
6.21     304
        ...
5.12     215
2.89     215
4.55     210
0.50     149
10.00    129
Name: count, Length: 951, dtype: int64

Tumor_Location
Parietal      50187
Occipital     50081
Temporal      49992
Frontal       49884
Cerebellum    49856
Name: count, dtype: int64

MRI_Findings
Abnormal    83737
Severe      83208
Normal      83055
Name: count, dtype: int64

Genetic_Risk
1     2598
89    2574
29    2572
52    2568
3     2561
      ...
93    2390
40    2386
45    2361
37    2348
0     2337
Name: count, Length: 101, dtype: int64

Smoking_History
Yes    125150
No     124850
Name: count, dtype: int64

Alcohol_Consumption
Yes    125173
No     124827
Name: count, dtype: int64

Radiation_Exposure
Low       83513
Medium    83480
High      83007
Name: count, dtype: int64

Head_Injury_History
Yes    125029
No     124971
Name: count, dtype: int64

Chronic_Illness
Yes    125321
No     124679
Name: count, dtype: int64

Blood_Pressure
146/117    70
117/106    70
154/108    68
161/88     68
143/85     68
           ..
126/68     26
137/84     25
159/89     25
171/89     22
122/101    18
Name: count, Length: 5551, dtype: int64

Diabetes
No     125216
Yes    124784
Name: count, dtype: int64

Tumor_Type
Benign       125204
Malignant    124796
Name: count, dtype: int64

Treatment_Received
Chemotherapy    62719
Radiation       62383
Surgery         62150
Name: count, dtype: int64

Survival_Rate(%)
23    2927
67    2901
37    2897
16    2886
42    2876
      ...
79    2695
17    2675
49    2671
57    2667
51    2662
Name: count, Length: 90, dtype: int64

Tumor_Growth_Rate
Slow        83390
Rapid       83379
Moderate    83231
Name: count, dtype: int64

Family_History
No     125036
Yes    124964
Name: count, dtype: int64

Symptom_Severity
Severe      83554
Mild        83481
Moderate    82965
Name: count, dtype: int64

Brain_Tumor_Present
No     125118
Yes    124882
Name: count, dtype: int64

**Analisis:**

Fitur dengan kategori paling banyak adalah fitur `Blood_Pressure` sebanyak 5.551 kategori. Hal ini disebabkan karena setiap individu pasien pasti mempunyai tekanan darah yang relatif berbeda dibanding pasien lainnya, sehingga beragam kategori pada fitur `Blood_Pressure` sudah dipastikan terjadi. Adapun fitur dengan kategori paling sedikit, yakni `Smoking_History`, `Alcohol_Consumption`, `Head_Injury_History`, `Chronic_Illness`, `Diabetes`, `Tumor_Type`, `Family_History`, dengan masing-masing fitur hanya memiliki 2 kategori yang isinya 'Yes' dan 'No'

#**6. Dataset Summary**

In [11]:
df.describe()

                 Age     Tumor_Size   Genetic_Risk  Survival_Rate(%)
count  250000.000000  250000.000000  250000.000000     250000.000000
mean       46.962424       5.251768      49.998916         54.481532
std        24.517143       2.742576      29.178031         25.999932
min         5.000000       0.500000       0.000000         10.000000
25%        26.000000       2.870000      25.000000         32.000000
50%        47.000000       5.260000      50.000000         55.000000
75%        68.000000       7.630000      75.000000         77.000000
max        89.000000      10.000000     100.000000         99.000000

In [12]:
df.describe(include="object")

,Gender,Country,Tumor_Location,MRI_Findings,Smoking_History,Alcohol_Consumption,Radiation_Exposure,Head_Injury_History,Chronic_Illness,Blood_Pressure,Diabetes,Tumor_Type,Treatment_Received,Tumor_Growth_Rate,Family_History,Symptom_Severity,Brain_Tumor_Present
count,250000,250000,250000,250000,250000,250000,250000,250000,250000,250000,250000,250000,187252,250000,250000,250000,250000
unique,3,12,5,3,2,2,3,2,2,5551,2,2,3,3,2,3,2
top,Male,Brazil,Parietal,Abnormal,Yes,Yes,Low,Yes,Yes,146/117,No,Benign,Chemotherapy,Slow,No,Severe,No
freq,83407,20985,50187,83737,125150,125173,83513,125029,125321,70,125216,125204,62719,83390,125036,83554,125118

**Statistik deskriptif kolom numerik.**

Rata-rata dan median hampir sama pada semua kolom, yakni
1. Age (46,96 dan 47)
2. Tumor_Size (5,25 dan 5,26)
3. Genetic_Risk (50,00 dan 50)
4. Survival_Rate (54,48 dan 55)

Sehingga sebaran nilainya cenderung simetris. Rentang nilai masing-masing adalah Age 5-89, Tumor_Size 0,5-10,0, Genetic_Risk 0-100, dan Survival_Rate 10-99.


**Statistik deskriptif kolom kategorikal.**

Seluruh kolom kategorikal terisi 250.000 baris, kecuali Treatment_Received yang terisi 187.252 baris karena teks 'None' terbaca sebagai NaN oleh pandas. Frekuensi kategori teratas hampir sama dengan kategori lainnya, misalnya `Gender` (Male 83.407 dari 250.000), `Smoking_History` (Yes 125.150), dan target `Brain_Tumor_Present` (No 125.118), sehingga tidak ada kategori yang dominan.